create table if not exists public.module_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  module_index integer not null,
  best_score numeric(5,2) not null default 0,
  passed boolean not null default false,
  attempts_count integer not null default 0,
  passed_at timestamptz null,
  updated_at timestamptz not null default now(),
  primary key (user_id, module_slug)
);

create table if not exists public.module_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  module_index integer not null,
  answers jsonb not null,
  score numeric(5,2) not null,
  passed boolean not null,
  created_at timestamptz not null default now()
);

alter table public.module_progress enable row level security;
alter table public.module_attempts enable row level security;

drop policy if exists "module_progress_select_own" on public.module_progress;
create policy "module_progress_select_own"
on public.module_progress
for select
using (auth.uid() = user_id);

drop policy if exists "module_progress_insert_own" on public.module_progress;
create policy "module_progress_insert_own"
on public.module_progress
for insert
with check (auth.uid() = user_id);

drop policy if exists "module_progress_update_own" on public.module_progress;
create policy "module_progress_update_own"
on public.module_progress
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "module_attempts_select_own" on public.module_attempts;
create policy "module_attempts_select_own"
on public.module_attempts
for select
using (auth.uid() = user_id);

drop policy if exists "module_attempts_insert_own" on public.module_attempts;
create policy "module_attempts_insert_own"
on public.module_attempts
for insert
with check (auth.uid() = user_id);
